subscription_id="6596c3ff-1969-4352-97dc-d3cc102c7b8d"
admin_username="centos"
ssh_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJOAczv0XGAITRX+NVSXi2IBbFXWik+/mbKrOymFl3HpBAkOOL+k9OA8sG0GBENj4Fs81Krv6HwFojH3PQBfgO0cE/d9+dkZUmC6dYH3Hjc/1M0AxxrSpBUgWaoO0BiS3Mhqg/2guCOVtn4/Vji6hA0tr3k1OLN2i6nnhk7bRfsI/MQLGRXv5EUNyrAlAvDOlaexqWE0GI+u4FbWYXJo6HA/deAtBhjLyKA+H4XVcgqkygjnhwLl8Myf3wBEsZQx+EH8fJ62i9iki1phvZJGXrQLfzDuUl9lx7DK4WVmmkMjryVLYRSh4apSVx34NyUOu604zz7s0ey7jTsB7pixJ5"
location="West US 2"
name_prefix="ichsnp-iics-qa-perf1-ma"
resource_group="IICHS-MANAGEMENTPLANE-USWEST2"
vnet_resource_group="INFRASTRUCTURE-DEV-VNET-USWEST2"
vnet_name="IICHS-MANAGEMENTPLANE-USWEST2-NP"
vm_size="Standard_D2s_v3"
subnet="OPS"
tags={
    # Name            ="ichsnp-westus2-consul"
    NAME            ="ichsnp-iics-qa-perf1-ma"
    APPLICATIONROLE ="MGMT"
    BUSINESSENTITY  ="CLOUDTRUST"
    ALERTGROUP      ="OPS_TEAM"
    SERVICENAME     ="CONSUL"
    SERVICEENTITY   ="CONSUL"
    OWNEREMAIL      ="CTOps@INFORMATICA.COM"
    BUSINESSUNIT    ="INFRASTRUCTURE"
    POD             ="NOPOD"
    APPLICATIONENV  ="QA"
    RUNNINGSCHEDULE ="00:00:23:59:1-7"
    ISAASTYPE       ="BASTION"
    SSHCA           ="YES"
    prometheus      ="node-exporter"
  }
image="/subscriptions/3d1a4cb3-087d-4c0c-90d0-ed3f2951af88/resourceGroups/Infa-Production-Images/providers/Microsoft.Compute/galleries/ubiimagegallery/images/ctcentos7def/versions/2023.04.2" # insert latest image
admin_password="M3sh@dmin!"
sa_account_name="iicsqaperf1" #storage_account_name
sa_account_key="6+i784BQcVDmWkXzrGQLPgU3FwUwTQX3RMMka2XvnNdAIiGCC0Ru9926OlGRQIhZ2Iz3ycfvJp4O+AStd5Orqw==" #storage_access_key
sa_share_name="iicsqaperf1"
consul_encryptkey="iCdqbZJjPoa/g9Z49cOnbg==" #consul_encrypt_key
sa_datacenter="IICS-QA-PERF1-MA" # insert consul_datacenter
vault_url="https://ha-vault.aks.iicsqa.uswest2.cloudtrust.rocks"
vault_id="e330bd54-78cd-4149-b402-b7599222347b"
kafka_host=["b-1.lamm-qa-elk-kafka.60xsom.c5.kafka.us-west-2.amazonaws.com:8443" ,"b-2.lamm-qa-elk-kafka.60xsom.c5.kafka.us-west-2.amazonaws.com:8444" ,"b-3.lamm-qa-elk-kafka.60xsom.c5.kafka.us-west-2.amazonaws.com:8445" ,"b-4.lamm-qa-elk-kafka.60xsom.c5.kafka.us-west-2.amazonaws.com:8446" ,"b-5.lamm-qa-elk-kafka.60xsom.c5.kafka.us-west-2.amazonaws.com:8447" ,"b-6.lamm-qa-elk-kafka.60xsom.c5.kafka.us-west-2.amazonaws.com:8448"]
kafka_topic="lamm-elk-qa-kafka-cloudtrust"
backup_sa_share_name="backup"
sendmail_url="mailnp-westus2.az.cloudtrust.rocks"
consul_cluster="ichsnp-iics-qa-perf1-ma"
